homework/001/vk/prof/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from prof.views import ProfilePageView, MyFriendsView
from . import views
from django.urls import path

urlpatterns = [
    # path('<str:prof_url>', views.prof_page)
    path('<str:prof_url>', login_required(ProfilePageView.as_view()), name='my_profile'),
    path('<str:prof_url>/friends', login_required(MyFriendsView.as_view()), name='my_friends'),
]

homework/001/vk/vk/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework import routers
from prof import views as prof_views
from walls import views as walls_views

router = routers.DefaultRouter()
router.register(r'posts', walls_views.PostViewSet)
router.register(r'profiles', prof_views.ProfilePageViewSet)

urlpatterns = [
    path('login/', include('login.urls')),
    path('rest/', include(router.urls)),
    path('walls/', include('walls.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('admin/', admin.site.urls),
    url('messages/', include(('msg.urls', 'msg'), namespace='msg')),
    url('prof/', include(('prof.urls', 'prof'), namespace='prof'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

homework/001/vk/msg/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from vk.settings import CUT_MSG_TEXT_LENGTH


class Mes(models.Model):
    sender = models.ForeignKey(User, related_name='msg_send', on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name='msg_received', on_delete=models.CASCADE)
    read = models.BooleanField(default=False)
    text = models.TextField()
    date_added = models.DateTimeField(default=now)

    def cut(self):
        if CUT_MSG_TEXT_LENGTH >= len(self.text):
            return self.text[:CUT_MSG_TEXT_LENGTH]
        else:
            return self.text[:CUT_MSG_TEXT_LENGTH] + '...'

homework/001/vk/prof/models.py
from django.db import models
from page.models import Page
from community.models import VerifiedMixin
from documents.models import DocumentsMixin
from django.contrib.auth.models import User


class ProfilePage(Page, VerifiedMixin, DocumentsMixin):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    middle_name = models.CharField(max_length=40)
    d_o_b = models.DateField()
    subscribe_to = models.ManyToManyField('prof.ProfilePage', blank=True, related_name="subscribers")

homework/001/vk/prof/forms.py
from django.core import validators
from django.forms import ModelForm, Textarea, FileInput, forms
from walls.models import Post


class PostForm(ModelForm):
    img = forms.FileField(validators=[validators.validate_image_file_extension])

    class Meta:
        model = Post
        fields = ['text', 'img']
        widgets = {
            'text': Textarea(attrs={'class': 'form-control'})
        }

homework/001/vk/prof/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from rest_framework.viewsets import ModelViewSet

from prof.models import ProfilePage
from walls.models import Post
from .forms import PostForm
from .serializers import ProfilePageSerializer


def prof_page(request, prof_url):
    profile = ProfilePage.objects.get(url_address=prof_url)
    user = request.user
    if request.method == 'POST' and user.has_perm('walls.add_post'):
        form = PostForm(request.POST, request.FILES)
        print(form.errors)
        if form.is_valid():
            post = form.save(commit=False)
            post.location = profile
            post.author = ProfilePage.objects.get(user=request.user)
            post.save()
    friends = ProfilePage.objects.order_by('?').filter(subscribe_to__id__contains=profile.id)
    posts = Post.objects.filter(location=profile).order_by('-date_added')
    form = PostForm()
    context = {'profile': profile, 'friends': friends, 'posts': posts, 'form': form}
    return render(request, 'prof/current_prof.html', context)


class ProfilePageViewSet(ModelViewSet):
    queryset = ProfilePage.objects.all()
    serializer_class = ProfilePageSerializer

    def perform_create(self, serializer):
        print('lalal')


class ProfilePageView(TemplateView):
    template_name = 'prof/current_prof.html'

    def get_context_data(self, **kwargs):
        context = super(ProfilePageView, self).get_context_data(**kwargs)
        prof_url = context.get('prof_url')
        profile = ProfilePage.objects.get(url_address=prof_url)
        context['profile'] = profile
        context['friends'] = ProfilePage.objects.order_by('?').filter(subscribe_to__id__contains=profile.id)
        context['posts'] = Post.objects.filter(location=profile).order_by('-date_added')
        context['form'] = PostForm()
        return context


class MyFriendsView(ListView):
    template_name = "prof/my_friends.html"

    context_object_name = 'friends'

    def get_queryset(self):
        subscribe_to_me = ProfilePage.objects.filter(Q(subscribe_to__url_address__contains=self.kwargs['prof_url']))
        return ProfilePage.objects.filter(subscribe_to=subscribe_to_me)

homework/001/vk/prof/templates/prof/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My profile</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/app2.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.1/css/mdb.min.css" rel="stylesheet"></head>
<body>
<style>
    .main{
        margin-top: 30px;
    }
</style>
<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.2.1/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.1/js/mdb.min.js"></script>

{% block content %}{% endblock content %}
</body>
</html>

homework/001/vk/prof/templates/prof/current_prof.html
{% extends 'prof/base.html' %}
{% load static %}

{% block content %}
    <nav class="mb-1 navbar navbar-expand-lg navbar-light">
        <div class="container">
            <a class="navbar-brand" href="#">IAPOLLY</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-4"
                    aria-controls="navbarSupportedContent-4" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent-4">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link waves-effect waves-light" href="#">
                            <i class="fas fa-envelope"></i> Contact
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect waves-light" href="#">
                            <i class="fas fa-gear"></i> Settings</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle waves-effect waves-light" id="navbarDropdownMenuLink-4"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-user"></i> Profile </a>
                        <div class="dropdown-menu dropdown-menu-right dropdown-info"
                             aria-labelledby="navbarDropdownMenuLink-4">
                            <a class="dropdown-item waves-effect waves-light" href="#">My account</a>
                            <a class="dropdown-item waves-effect waves-light" href="{% url 'logout' %}">Log out</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <img width="100%" src="{{ profile.page_picture.file.url }}" alt="">
            </div>
            <div class="col-9">
                <h3>
                    {{ profile.first_name }}
                    {{ profile.last_name }}
                </h3>
                <div>
                    Status: {{ profile.status }}
                </div>
                <div>
                    Сity: {{ profile.location.city }} <br>
                    Birthday: {{ profile.d_o_b }}
                </div>
                <br>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-3">
                <div id="friends">
                    <a href="{% url 'prof:my_friends' prof_url='iapolly' %}">My friends</a>
                </div>
            </div>
            <div class="col-md-9">
                <div id="posts">
                    <h3>Posts</h3>
                    <hr>
                    <form id="post-form" method="post" enctype="multipart/form-data">
                        <div id="count">300</div>
                        {% csrf_token %}
                        {{ form.text }}
                        {{ form.img }}
                        <button type="submit" class="save btn btn-sm btn-default">
                            <i class="fab fa-telegram-plane"></i>
                        </button>
                    </form>
                    <hr>
                    {% for post in posts %}
                        <div class="card">
                        <div class="card-title text-right">
                            {% if user == profile.user  %}
                            <a href="{% url 'edit_post' post_id=post.id %}"><i class="fas fa-pen-square"></i></a>
                            {% endif %}
                        </div>
                            <div class="card-body">
                                {{ post.author.first_name }} <br>
                                <hr>
                                {{ post.text }}
                                <br>
                                {% if post.img %}
                                    <img width="90%" src="{{ post.img.url }}" alt="">
                                {% endif %}
                            </div>
                            <div class="card-footer text-center">
                                <img class="like" id="{{ post.id }}" src="{% static 'img/notlike.png' %}">
                            </div>
                        </div>
                        <hr>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <style>
        #id_text {
            height: 100px;
        }
    </style>
    <script>
        $('.like').on('click', function (event) {
            post_id = event.target.id;
            $.ajax({
                url: "/walls/like/",
                dataType: 'json',
                data: {
                    post_id: post_id,
                },
                success: function (data) {
                    likesCount = data.data;
                    document.getElementById(post_id).src = '{% static 'img/like.png' %}'
                },
                error: function (data) {
                    console.log('sad')
                }
            });
        });

        $(document).ready(function () {
            $("#id_text").keyup(function () {
                var box = $(this).val();
                var count = 300 - box.length;

                if (box.length <= 300) {
                    $('#count').html(count);
                } else {
                    alert(' Full ');
                }
                return false;
            });

        });
    </script>

    {#</script>#}
{% endblock content %}

homework/001/vk/prof/templates/prof/my_friends.html
{% extends 'prof/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h4>FRIENDS</h4>
            <ul>
                {% for f in friends %}
                    <li class="friend">{{ f.first_name }} </li>
                {% endfor %}
            </ul>
            </div>
        </div>
    </div>

{% endblock content %}